name: student_budget_ai
description: An AI-powered budget tracking app designed specifically for students

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Navigation
  go_router: ^12.1.3

  # Charts & Visualization
  fl_chart: ^0.65.0

  # AI & ML
  google_ml_kit: ^0.16.0

  # Speech Recognition
  speech_to_text: ^6.6.0

  # HTTP & API
  http: ^1.1.2

  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  image_picker: ^1.0.5
  shared_preferences: ^2.2.2

  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf