name: flutter_ml_app
description: A Flutter app with ML Kit, Hive, and speech recognition.

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^12.1.3
  fl_chart: ^0.65.0
  google_ml_kit: ^0.16.0
  speech_to_text: ^6.6.0
  http: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
